### ISSUE TITLE
Load data error ?

### ISSUE THREAD

**Issue by yiboin** [layumi/2016_person_re-ID#1]
运行环境：centos7 /matlab2014 
运行test2/test_gallery_res.m 的时候，提示data/imagenet-resnet-50-dag.mat Not a binary mat file , try load -ASCII。
运行train_id_net_res_2stream.m的时候，也是同样的问题。
不知为何，求解点

**Comment by layumi** [comment]
@yiboin  Please check that you have downloaded the following files in this dir correctly.
https://github.com/layumi/2016_person_re-ID/tree/master/data

**Comment by yiboin** [comment]
**@layumi**  你好！我又重新把代码下载了一遍，一共20.81MB，然后我在matlab里，尝试直接加载数据**load('D:\reid\2016_person_re-ID-master\data\imagenet-resnet-50-dag.mat')** 时,显示 ***"错误使用 load
无法读取 MAT 文件"D:\reid\2016_person_re-ID-master\data\imagenet-resnet-50-dag.mat: 不是二进制 MAT 文件。请尝试执行 LOAD -ASCII 以便以文本形式读取"***   ？
还望指点，感谢！

**Comment by layumi** [comment]
@yiboin The size of the model  is about 90~100MB. Please directly download the model in the dir.

**Comment by yiboin** [comment]
**@layumi**  I am sorry to bother you again!  I can only download the mat file of [imagenet-resnet-50-dag.mat](http://www.vlfeat.org/matconvnet/pretrained/) but not find **"resnet52_market.mat","net-epoch-75.mat",and "vl_demo_svm_data.mat"**. Could you give me a link on BaiDu to download these files?
**Thank you!!**

**Comment by layumi** [comment]
@yiboin Thank you! It's my fault. Today I double-check the 'git clone'. I use the git-lfs to store the large models. But this reposity may be over data quota (download limitation).
Alternatively, you can download the complete codes from [GoogleDriver](https://drive.google.com/file/d/0B0VOCNYh8HeRV29EaGRXWFZPbHM/view?usp=sharing) or [BaiduYun] (https://pan.baidu.com/s/1mhKoQ4S). Sorry for my mistake.

**Comment by yiboin** [comment]
**@layumi** Thank you for the complete codes!  I can run the demo without errors. Thanks!!
