### ISSUE TITLE
download link for pre-trained models

### ISSUE THREAD

**Issue by saraershadi** [layumi/2016_person_re-ID#16]
Hello, 

I want to use your provided link for downloading the pre-trained models from wget in Linux terminal.
But google drive link does not work and is unable to establish a ssl connection.
The other link does not work.
I am using this command.
wget https://drive.google.com/drive/folders/0B0VOCNYh8HeRWks0V24xTlpKWkU

Thank you 
Sarah

**Comment by layumi** [comment]
Hi @saraershadi 
GoogleDrive does not provide the open link for wget directly.
So you need to open this link in your browser and download the files by the browser.

**Comment by saraershadi** [comment]
I am only access to the terminal of the server and it is not possible to download this file locally and then transmit it to the server since the server has much more network speed than the local computers.
Do you know how can download it from linux server directly ?

Thank you.
Sarah

**Comment by layumi** [comment]
Dear @saraershadi 
Actually, I recommend you download the files on your laptop then upload to your server.
`scp source.zip  your@remote:/home/target_folder`

**Comment by saraershadi** [comment]
I know what you mean but  I have a very low-speed net with limited download size on my laptop. 
But through the server, I can download with unlimited size and speed.

**Comment by layumi** [comment]
@saraershadi 
You may use google drive api. https://github.com/googledrive/PyDrive
But it may be complicate to use.

So you may directly train the model by yourself.
Follow the next step in README

**Comment by saraershadi** [comment]
Thank you, I download the model finally.
