### ISSUE TITLE
Attempt to execute SCRIPT vl_nnconv as a function:

### ISSUE THREAD

**Issue by saraershadi** [layumi/2016_person_re-ID#17]
Hello, 

I am using gcc 4.7 and g++ 4.7. and Matlab version Matlab2016a. They are compatible with making the mex files.
I used the command vl_compilenn to compile the files in Matlab folder and making the mex files.
Now mex files of are existed in matlab/mex folder.

I called matlab in test folder and use this command to add the subdirectory and mex files.
addpath(genpath(../matlab))
But when I tried to run the test_gallery_query_crazy.m file it reaches to this error.
>> Attempt to execute SCRIPT vl_nnconv as a function:

What is the source of this error ?

Thanks in advance.
Sarah

**Comment by layumi** [comment]
Dear @saraershadi 
Matlab will find the mex file first. If matlab does not  find mex file, it will find the script file.
So the error raise 'Attempt to execute script xxx'

Are there any mex files generated in `./matlab/mex` folder?
Or you may try to compile it again. 

This website may help you.
http://www.vlfeat.org/matconvnet/install/

**Comment by saraershadi** [comment]
Dear @layumi 
Yes, mex file are produced and are existed in the matlab/mex folder . 
I have used the command 
vl_compilenn
vl_setupnn
vl_testnn
and all of them run successfully.
But when I want to run the test_gallery_query_crazy.m file it reaches to error about 
Attempt to execute SCRIPT vl_nnconv as a function:
I have attached a picture of the location of mex file.

Thank you.
Sarah


![mex](https://user-images.githubusercontent.com/5570746/34976315-4461715e-faab-11e7-9a8a-ce873d9bf263.png)

**Comment by saraershadi** [comment]
Also when I sued the command 
run ../matlab/vl_setupnn 
it reaches to several warnings.

----------------------------------------------------------------------------------------------

Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run (line 43)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run (line 43)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 12)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 12)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 13)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 13)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 14)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 14)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 15)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 15)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 16)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 16)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run>resetCD (line 102)
  In run>@()resetCD(startDir,fileDir) (line 46)
  In onCleanup/delete (line 60)
  In run (line 97)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run>resetCD (line 102)
  In run>@()resetCD(startDir,fileDir) (line 46)
  In onCleanup/delete (line 60)
  In run (line 97)
>> clc
>> run ../matlab/vl_setupnn.m
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run (line 43)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run (line 43)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 12)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 12)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 13)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 13)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 14)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 14)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 15)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 15)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 16)
  In run (line 96)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In path (line 109)
  In addpath (line 88)
  In vl_setupnn (line 16)
  In run (line 96)
Warning: Function labindex has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run>resetCD (line 102)
  In run>@()resetCD(startDir,fileDir) (line 46)
  In onCleanup/delete (line 60)
  In run (line 97)
Warning: Function numlabs has the same name as a MATLAB builtin. We suggest you rename the function
to avoid a potential name conflict.
> In run>resetCD (line 102)
  In run>@()resetCD(startDir,fileDir) (line 46)
  In onCleanup/delete (line 60)
  In run (line 97)
-----------------------------------------------------------------------

**Comment by saraershadi** [comment]
Dear @layumi 

This is the error,
----------------------------------------------------------
Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).
---------------------------------------------------------- 
Should I compile matconvenet in GPU ?
Can this function run in CPU mode?
