### ISSUE TITLE
Implementation on Keras

### ISSUE THREAD

**Issue by ahangchen** [layumi/2016_person_re-ID#18]
https://github.com/ahangchen/rank-reid/blob/master/pretrain/pair_train.py

It's very simple to implement this [model](https://github.com/ahangchen/rank-reid/blob/release/pretrain/pair_train.py#L138) on Keras. The most complicated part is [image-pairs' construction](https://github.com/ahangchen/rank-reid/blob/release/pretrain/pair_train.py#L93)

Reach 78.3% on Market-1501.

**Comment by layumi** [comment]
Thank you @ahangchen .
I stumbled across your code. It is great and I really enjoy it. 
I will add your code link into README.
Many Thanks.

**Comment by ahangchen** [comment]
Thank you @layumi , I will add more instruction about this network in the repository.
