### ISSUE TITLE
Undefined function or variable 'net'

### ISSUE THREAD

**Issue by rmxhhh** [layumi/2016_person_re-ID#21]
@layumi hi，i try to run your code,but there is a mistake,when i run the"train_id_net_res_2stream.m",it shows
`cnn_train_dag: resuming by loading epoch 75
Undefined function or variable 'net'。

wrong cnn_train_dag>loadState (line 406)
net = dagnn.DagNN.loadobj(net) ;

wrong cnn_train_dag (line 67)
  [net, state, stats] = loadState(modelPath(start)) ;

wrong train_id_net_res_2stream (line 34)
printf(cnn_train_dag(net, imdb, @getBatch,opts) );`
can you tell me what's wrong with it,I have tried this problem for several days and have not solved this problem.thank you!

**Comment by layumi** [comment]
Hi @rmxhhh
You have trained model with 75 epochs.  Now you want to resume training?

If you want to start a new training,  remember to change the name of `opts.train.expDir`.
Or `opts.train.continue = false; `

**Comment by rmxhhh** [comment]
@layumi  It works! Tank you!

**Comment by rmxhhh** [comment]
Hi,@layumi
 Hi,I'm sorry to bother you again,i have another mistake when i run the code.When i run the epoch 2,it does not draw the result and there is a mistake shows
`Error using checkArgsForHandleToPrint
The input parameters of the handle contain non-handle values.

wrong in checkArgsForHandleToPrint

wrong in print>LocalCreatePrintJob (line 216)
    handles = checkArgsForHandleToPrint(0, varargin{:});

wrong in print (line 38)
    [pj, inputargs] = LocalCreatePrintJob(varargin{:});

wrong in cnn_train_dag (line 139)
    print(1, modelFigPath, '-dpdf') ;

wrong in train_id_net_res_2stream (line 34)
[net,info] = cnn_train_dag(net, imdb, @getBatch,opts) ;`

But it run successfully when i run the epoch 1 and it has draw the result.

**Comment by layumi** [comment]
@rmxhhh 
It seems to be a Matlab problem. Could you try another machine?
Or you could disable the print function to train.

**Comment by rmxhhh** [comment]
I have tried other machines,but  the same error occurred.So i tried to disable the print function and it run successfully.Thank you very much.

**Comment by rmxhhh** [comment]
@layumi 
I have tried other machines,but the same error occurred.So i tried to disable the print function and it run successfully.Thank you very much. @
