### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by finger-monkey** [layumi/2016_person_re-ID#25]
老哥，请问要如何得到您A Discriminatively Learned CNN Embedding for Person Re-identification论文那张分类结构的可视化图。老哥有写过python版本的吗？
![image](https://user-images.githubusercontent.com/52326609/96261712-5e63cb00-0ff3-11eb-8fb5-40a0ad02d6a2.png)

**Comment by layumi** [comment]
诶，，
我那时候是用matlab。你可以参考 https://github.com/layumi/bhtsne <https://github.com/layumi/bhtsne> 
应该也可以改成python来调用，很方便。


Zhedong Zheng
University of Technology Sydney
http://zdzheng.xyz <http://zdzheng.xyz/>

**Comment by finger-monkey** [comment]
好的谢谢哲东哥（献上我的膝盖）
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "layumi/2016_person_re-ID"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月17日(星期六) 上午7:39
收件人:&nbsp;"layumi/2016_person_re-ID"<2016_person_re-ID@noreply.github.com&gt;;
抄送:&nbsp;"Finger Monkey"<1286670508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [layumi/2016_person_re-ID] 可视化 (#25)





 诶，，
 我那时候是用matlab。你可以参考 https://github.com/layumi/bhtsne <https://github.com/layumi/bhtsne&gt; 
 应该也可以改成python来调用，很方便。
 
 
 Zhedong Zheng
 University of Technology Sydney
 http://zdzheng.xyz <http://zdzheng.xyz/&gt;
 
 
 
 
 
 
 &gt; On 17 Oct 2020, at 12:08 am, finger-monkey <notifications@github.com&gt; wrote:
 &gt; 
 &gt; 
 &gt; 老哥，请问要如何得到您A Discriminatively Learned CNN Embedding for Person Re-identification论文那张分类结构的可视化图。老哥有写过python版本的吗？
 &gt;  <https://protect-au.mimecast.com/s/ePDwCZY1o3fDRz9jfz_Xic?domain=user-images.githubusercontent.com&gt;
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub <https://protect-au.mimecast.com/s/JO2NC1WLn2Ikm8NZfGQpGe?domain=github.com&gt;, or unsubscribe <https://protect-au.mimecast.com/s/F1h3C2xMo3sRG7zmsB78Tv?domain=github.com&gt;.
 &gt;
