### ISSUE TITLE
how to get the result of single query and multi query

### ISSUE THREAD

**Issue by JoyLuo** [layumi/2016_person_re-ID#6]
hi @layumi 
    the result of your code is based on single query. single query in you code is that every image in query dateset to get the search result in gallery dateset.
    1, am i right about single query? 
    2, how to get the result of multi query?
    
    and thanks for your kindly

**Comment by layumi** [comment]
Hi @JoyLuo 
1. You are right with the concept of single query.
2. Actually, we can get a sequence of the query under one camera. Then we can use every image in this sequence to extract a query mean feature (mean of feature extracted from several images).
We call it multi-query.  If we use this feature to do person retrieval, we usually get a better result.  
But it use additional images (in gt_bboxes).  You can find more detail in the paper of Market1501 and baseline code in http://liangzheng.org/Project/project_reid.html.

**Comment by layumi** [comment]
I just add multi-query evaluation code in https://github.com/layumi/2016_person_re-ID/tree/master/evaluation
You can refer to it.

**Comment by JoyLuo** [comment]
thanks a lot
