### ISSUE TITLE
how to make the activation maps

### ISSUE THREAD

**Issue by JoyLuo** [layumi/2016_person_re-ID#8]
Dear @layumi 
    the visualization of the activation maps in your paper is wonderful. and i am very curiosity of how to make it. i got no answer after searching the internet. so please tell me the skill when you have relax time.
    thanks a lot.

**Comment by layumi** [comment]
Hi @JoyLuo 
I take MatConvnet as an example.
You can get the middle result like 7\*7\*2048 (the activation before pool5).
Then sum it to 7\*7 as a gray-scale image.  
There is a tool to change this gray-scale image to heatmap(red & blue).
I will provide the code recently.

**Comment by layumi** [comment]
Hi @JoyLuo 
I have uploaded the heatmap code in https://github.com/layumi/2016_person_re-ID/tree/master/demo_for_heatmap. You can check it.

**Comment by JoyLuo** [comment]
Hi @layumi 
it is so great, Thanks for your kindness.
